Camera Essentials: https://raspberrypi.org/magpi-issues/Essentials_Camera_v1.pdf
Command Line: https://raspberrypi.org/magpi-issues/Essentials_Bash_v1.pdf
GPIO Zero Essentials: https://raspberrypi.org/magpi-issues/Essentials_GPIOZero_v1.pdf
Issue 40: https://raspberrypi.org/magpi-issues/MagPi40.pdf
Issue 41: https://www.raspberrypi.org/magpi-issues/MagPi41.pdf
Issue 42: https://raspberrypi.org/magpi-issues/MagPi42.pdf
Issue 43: https://raspberrypi.org/magpi-issues/MagPi43.pdf
Issue 44: https://raspberrypi.org/magpi-issues/MagPi44.pdf
Issue 45: https://raspberrypi.org/magpi-issues/MagPi45.pdf
Issue 46: https://raspberrypi.org/magpi-issues/MagPi46.pdf
Issue 47: https://raspberrypi.org/magpi-issues/MagPi47.pdf
Issue 48: https://raspberrypi.org/magpi-issues/MagPi48.pdf
Issue 49: https://raspberrypi.org/magpi-issues/MagPi49.pdf
Issue 50: https://raspberrypi.org/magpi-issues/MagPi50.pdf
Issue 51: https://raspberrypi.org/magpi-issues/MagPi51.pdf
Issue 52: https://raspberrypi.org/magpi-issues/MagPi52.pdf
Issue 53: https://raspberrypi.org/magpi-issues/MagPi53.pdf
Issue 54: https://raspberrypi.org/magpi-issues/MagPi54.pdf
Issue 55: https://raspberrypi.org/magpi-issues/MagPi55.pdf
Issue 56: https://raspberrypi.org/magpi-issues/MagPi56.pdf
Issue 57: https://raspberrypi.org/magpi-issues/MagPi57.pdf
Issue 58: https://raspberrypi.org/magpi-issues/MagPi58.pdf
Issue 59: https://raspberrypi.org/magpi-issues/MagPi59.pdf
Issue 60: http://magpi.cc/2uEcJgS
Learn C Essentials: https://www.raspberrypi.org/magpi-issues/Essentials_C_v1.pdf
MagPi 01: https://www.raspberrypi.org/magpi-issues/MagPi01.pdf
MagPi 02: https://www.raspberrypi.org/magpi-issues/MagPi02.pdf
MagPi 03: https://www.raspberrypi.org/magpi-issues/MagPi03.pdf
MagPi 04: https://www.raspberrypi.org/magpi-issues/MagPi04.pdf
MagPi 05: https://www.raspberrypi.org/magpi-issues/MagPi05.pdf
MagPi 06: https://www.raspberrypi.org/magpi-issues/MagPi06.pdf
MagPi 07: https://www.raspberrypi.org/magpi-issues/MagPi07.pdf
MagPi 08: https://www.raspberrypi.org/magpi-issues/MagPi08.pdf
MagPi 09: https://www.raspberrypi.org/magpi-issues/MagPi09.pdf
MagPi 10: https://www.raspberrypi.org/magpi-issues/MagPi10.pdf
MagPi 11: https://www.raspberrypi.org/magpi-issues/MagPi11.pdf
MagPi 12: https://www.raspberrypi.org/magpi-issues/MagPi12.pdf
MagPi 13: https://www.raspberrypi.org/magpi-issues/MagPi13.pdf
MagPi 14: https://www.raspberrypi.org/magpi-issues/MagPi14.pdf
MagPi 15: https://www.raspberrypi.org/magpi-issues/MagPi15.pdf
MagPi 16: https://www.raspberrypi.org/magpi-issues/MagPi16.pdf
MagPi 17: https://www.raspberrypi.org/magpi-issues/MagPi17.pdf
MagPi 18: https://www.raspberrypi.org/magpi-issues/MagPi18.pdf
MagPi 19: https://www.raspberrypi.org/magpi-issues/MagPi19.pdf
MagPi 20: https://www.raspberrypi.org/magpi-issues/MagPi20.pdf
MagPi 21: https://www.raspberrypi.org/magpi-issues/MagPi21.pdf
MagPi 22: https://www.raspberrypi.org/magpi-issues/MagPi22.pdf
MagPi 23: https://www.raspberrypi.org/magpi-issues/MagPi23.pdf
MagPi 24: https://www.raspberrypi.org/magpi-issues/MagPi24.pdf
MagPi 25: https://www.raspberrypi.org/magpi-issues/MagPi25.pdf
MagPi 26: https://www.raspberrypi.org/magpi-issues/MagPi26.pdf
MagPi 27: https://www.raspberrypi.org/magpi-issues/MagPi27.pdf
MagPi 28: https://www.raspberrypi.org/magpi-issues/MagPi28.pdf
MagPi 29: https://www.raspberrypi.org/magpi-issues/MagPi29.pdf
MagPi 30: https://www.raspberrypi.org/magpi-issues/MagPi30.pdf
MagPi 31: https://www.raspberrypi.org/magpi-issues/MagPi31.pdf
MagPi 32: https://www.raspberrypi.org/magpi-issues/MagPi32.pdf
MagPi 33: https://raspberrypi.org/magpi-issues/MagPi33.pdf
MagPi 34: https://raspberrypi.org/magpi-issues/MagPi34.pdf
MagPi 35: https://www.raspberrypi.org/magpi-issues/MagPi35.pdf
MagPi 36: https://www.raspberrypi.org/magpi-issues/MagPi36.pdf
MagPi 37: https://www.raspberrypi.org/magpi-issues/MagPi37.pdf
MagPi 38: https://www.raspberrypi.org/magpi-issues/MagPi38.pdf
MagPi 39: https://raspberrypi.org/magpi-issues/MagPi39.pdf
MagPi SE 1: https://www.raspberrypi.org/magpi-issues/MagPiSE1.pdf
Make Games: https://www.raspberrypi.org/magpi-issues/Essentials_Games_v1.pdf
Minecraft Essentials: https://raspberrypi.org/magpi-issues/Essentials_Minecraft_v1.pdf
Projects Book: https://raspberrypi.org/magpi-issues/Projects_Book_v1.pdf
Projects Book 2: https://www.raspberrypi.org/magpi-issues/Projects_Book_v2.pdf
Scratch Essentials: https://raspberrypi.org/magpi-issues/Essentials_Scratch_v1.pdf
Sense HAT Essentials: https://raspberrypi.org/magpi-issues/Essentials_SenseHAT_v1.pdf
Sonic Pi Essentials: https://raspberrypi.org/magpi-issues/Essentials_Sonic_Pi-v1.pdf
